### ISSUE TITLE
Ask a librarian widget updates

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#1122]

**Comment by binkylush** [comment]
**Summary from Karen S:**

On pages where you're using a LibAnswers or LibChat widget, search for these text strings in the widget code:

v2.libanswers.com

region-xx.libanswers.com
	
api2.libanswers.com
	
api2-xx.libanswers.com


Replace them with  psu.libanswers.com


**More info from Springshare...**

Important Note about Deprecation of Widget Endpoints

What is happening?
As part of our continuous effort to ensure the highest levels of security in our apps, we are sunsetting certain widget and API endpoints (listed below). These endpoints will stop working at the end of January 2023. This email contains instructions for how to identify any affected widgets and how to change them. We will remind you via [Lounge posts](https://lounge.springshare.com/discussion/1203/libanswers-libchat-important-note-about-deprecation-of-widget-endpoints), login messages, and email between now and the end of January 2023.

Any widgets created after January 1, 2022 are using the proper format. You can check a widget's creation date in Admin > Widgets and API or LibChat > Widgets. If all of your widgets were created after January 1, 2022, you do not need to do anything.

If one or more widgets were created before January 1, 2022, please read on.

How does this affect me?
You must check your Springshare apps and any other web pages where you have LibAnswers and/or LibChat widgets or API calls to see whether they are using any of the domains / URL patterns listed in the next section.

If so, update those widgets / API calls (as noted below) by the end of January 2023 or they will stop working.
If not, you do not need to do anything further.
The widget / API builder in LibAnswers always shows you the updated, current code / domain, regardless of when you created that widget. This means that inspecting your widgets on the pages they're being used is necessary, to see if they are using the old URLs below.

If you are using LibGuides, there are a couple of tools you can use to find the text strings listed below. One is the [Search & Replace tool](https://ask.springshare.com/libguides/faq/2782); the other is searching within your [Content > Assets area](https://ask.springshare.com/libguides/faq/1884), using the filters to limit by Type = Widget and adding each text string below to the Description filter.

What do I need to update?
In most cases, the widget or API URL just needs to be updated to use your LibAnswers site's domain instead of an older, app-wide domain. In one case of one LibChat URL, more of the URL pattern has changed.

What is my LibAnswers domain?

Your LibAnswers domain is part of the URL you share with your community. In the examples below, the bolded text is the domain of the system:

https://mylibrary.libanswers.com
https://answers.mylibrary.org
If your widgets / API calls are already referencing your own LibAnswers domain, you do not need to do anything further. Your widgets will continue to work as expected.

Update any widgets or API calls using these domains

Note: The xx in region-xx or api-xx below relates to the server region where your site is located (e.g., region-eu, region-au, region-ca).

On pages where you're using a LibAnswers or LibChat widget, search for these text strings in the widget code:

v2.libanswers.com
region-xx.libanswers.com
api2.libanswers.com
api2-xx.libanswers.com
Replace those domains with your LibAnswers domain.

Examples (your domain will be different): 

crabtownbaylibrary.libanswers.com
answers.springylibrary.org
answers.stateuniversity.edu
Also update any LibChat widgets using the following path

On pages where you're using a LibChat widget, search for this text string in the widget code:

v2.libanswers.com/chati.php?hash=
region-xx.libanswers.com/chati.php?hash=
Replace the above string(s) with:

yourLibAnswersDomain/chat/widget/

Examples of an updated URL section (your domain will be different):

crabtownbaylibrary.libanswers.com/chat/widget/
answers.stateuniversity.edu/chat/widget/
Note: If you are using your own domain (as noted above) but see that the domain ends in chat.php?hash=xxx, that is still correct and does not need to be changed. If you see that your domain includes chati.php? (where there is an "i" after chat") then that domain will need updating per the instructions above.

If you have any questions about this update, we encourage you to leave a comment below. If you have any concerns, please [let us know via our support form](https://ask.springshare.com/ask). As noted earlier, we will send reminders about this via email, Lounge posts, and login messages.

Thanks for your attention to this update, and as always, thanks for being on board!
