### ISSUE TITLE
Facet fields

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#21]
https://github.com/psu-libraries/psulib_blacklight/wiki/Blacklight-Catalog-Fields#facets

**Comment by ruthtillman** [comment]
We can make a new ticket for it, but documenting the logic we'll need to make the Online / In Library Facet work:

Library, 949m, is either ONLINE or another location. If it's online, we add Online. If it's anything else, we add At the Library. We should then make unique so we don't have like 10 At the Library entries for one work (or multiple Online ones).

Questions to follow up --  what about things that are on order or otherwise in processing? Are we just worried about whether online or not?

**Comment by banukutlu** [comment]
@ruthtillman are we ready to move this https://psu.app.box.com/notes/320774203905 to wiki?

**Comment by ruthtillman** [comment]
@banukutlu https://github.com/psu-libraries/psulib_blacklight/wiki/Blacklight-Catalog-Fields

**Comment by banukutlu** [comment]
@ruthtillman also for this one - could you pls make sure if we have a task for each facet field that needs to be mapped and displayed so that we can close this issue?

**Comment by ruthtillman** [comment]
@banukutlu this one I'm gonna have to poke a little more.

**Comment by cdmo** [comment]
Just reviewing this omnibus facets issue... can it be closed since the facets have been broken down into smaller issues? Or?

**Comment by ruthtillman** [comment]
Yes, I think so.


Ruth Kitchin Tillman
Cataloging Systems & Linked Data Strategist
Penn State University Libraries
Paterno Library 006 | 814-867-1038
rkt6@psu.edu<mailto:rkt6@psu.edu>

________________________________
