### ISSUE TITLE
Advanced Search updates

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#239]
Related to #46

Per https://github.com/psu-libraries/psulib_blacklight/wiki/Advanced-Search:

- Add as text field:
  - [x] Series
  - [x] Publisher
- Change to text field:
  - [x] Subject
  - [x] Publication date (perhaps two boxes?)
- Drop-downs should display every value which exists as a facet:
  - [x] Language
  - [x] Format 
- Add as dropdown
  - [x] Media Type 
  - [x] Library (not indexed yet)
  - ~[ ] Location (not indexed yet)~ see #269
- Remove from drop-down:
  - [x] Genre
  - [x] Call Number
  - [x] Subject (move up to text fields section)
- [x] Selects not populating on first load (turbolink load)
- [x] Change "more options" to "advanced search"

**Comment by ruthtillman** [comment]
Everything is looking great but Call Number doesn't seem to work when selected (either alone or with other fields). (however just the highest-letter call number is sufficient once it works, we don't need to break it down any more)

**Comment by cdmo** [comment]
I have a fix for this that we'll deploy soon, but, just wanted to mention that the reason that the classification facet shows up at all is kind of a fluke/bug. Blacklight Advanced Search automatically includes all pivot facets, I think it's a bug in the relationship between BLAS and BL. Anyway, I mention this because including this option wasn't in the [original spec](https://github.com/psu-libraries/psulib_blacklight/wiki/Advanced-Search) and was actually supposed to be removed according to the punch list at the top of this issue. So we definitely want it right, as just the first letter option. ?
