### ISSUE TITLE
Drop searches table

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#260]
Saved searches aren't needed anymore, we need to remove the table and disable this feature entirely. New migration.

If we decide we still need it then we need a scheduled task to clear the table periodically.

**Comment by ruthtillman** [comment]
So ran across an issue when navigating Prev/Next for these results. First we have:

![search-results-1](https://user-images.githubusercontent.com/2687749/114880313-f5a5b180-9dcf-11eb-9a56-25183bd7f890.png)

Then I go into an item:

![search-results-item-view](https://user-images.githubusercontent.com/2687749/114880384-0524fa80-9dd0-11eb-8a3e-86a040b74392.png)

and you see at the top there's a number which is _all_ the results in the Catalog, not just the search results number.

Then I navigate Next and most of y'all will recognize it as one of the first results for a "null" search (essentially a search all):

![search-results-next-this-doesn't-match](https://user-images.githubusercontent.com/2687749/114880564-27b71380-9dd0-11eb-93e8-eb11e9ec1ff8.png)

**Comment by awead** [comment]
@ruthtillman I was afraid this might happen. Since we're not saving the searches anymore, you loose your existing previous and next context. We'll need to re-enable storing of the searches if you want this functionality. But, we could store them differently. Some options would be:

1. Redis - store the searches with an expiration time (ex. 24 hours) and they'll be removed after that time has elapsed.
2. Client side cookies - keep a cookie in the user's browser cache.
3. Database - leave them where they originally were and truncate (remove) them on a scheduled basis.

I think my vote would be Redis. It's suuuuuper fast, and since it's only the query params for the search that we're storing, it'd be an easy switch.

**Comment by ruthtillman** [comment]
Thoughts are: Redis sounds good if it doesn't introduce too much overhead. cc @banukutlu ?

Otherwise, let's set up the removal on a regular basis.

**Comment by banukutlu** [comment]
> @ruthtillman I was afraid this might happen. Since we're not saving the searches anymore, you loose your existing previous and next context. We'll need to re-enable storing of the searches if you want this functionality. But, we could store them differently. Some options would be:
> 
> 1. Redis - store the searches with an expiration time (ex. 24 hours) and they'll be removed after that time has elapsed.
> 2. Client side cookies - keep a cookie in the user's browser cache.
> 3. Database - leave them where they originally were and truncate (remove) them on a scheduled basis.
> 
> I think my vote would be Redis. It's suuuuuper fast, and since it's only the query params for the search that we're storing, it'd be an easy switch.

I think I am inclined toward Redis as well, rather than having a dependency to mysql, also we might use Redis for other things as well and we already using it for MyAccount.

**Comment by ruthtillman** [comment]
@banukutlu @awead sounds good, then!
