### ISSUE TITLE
Home page facets

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#382]
Load for all facets is heavy. Let's test with just:

- Access
- Format
- Campus

Aha! Link: https://penn-state-university-libraries.aha.io/features/STPROJ-32

**Comment by ruthtillman** [comment]
Preferred would be:

* Access
* Format
* Campus
* Media Type
* Call Number

**Comment by cdmo** [comment]
Given the discussion I had on code4lib slack's blacklight channel, I am of the mind that we need to mitigate some other facet-related problems before implementing this. See #342

**Comment by banukutlu** [comment]
> Given the discussion I had on code4lib slack's blacklight channel, I am of the mind that we need to mitigate some other facet-related problems before implementing this. See #342

:100: and thanks for noting it here

**Comment by cdmo** [comment]
@ruthtillman @banukutlu I think it'd be a good time to work on this, can we add it to the current milestone of Hathi work? We can add these in and simply cache them hourly.

**Comment by banukutlu** [comment]
> @ruthtillman @banukutlu I think it'd be a good time to work on this, can we add it to the current milestone of Hathi work? We can add these in and simply cache them hourly.

sure, we can try it in the current milestone 👍  thanks

**Comment by ruthtillman** [comment]
Sounds good and if it slows things down too much or proves messy, we can pull back and determine if it's just not doable.

**Comment by cdmo** [comment]
This is sorta related because making the homepage facets expand by default seems like something you would want @ruthtillman right? Otherwise it kind of just hides the numbers and users might not get what the collapsed menus on the side are even (maybe?). It struck me that we collapse facets by default, globally. I guess I forgot! A lot of other catalogs on Blacklight don't do this. Here's a screenshot, all facets collapsed (the default): 

![Screen Shot 2020-06-12 at 10 47 06 PM](https://user-images.githubusercontent.com/523381/84558178-eb71dd00-acfe-11ea-8481-7d72780a41b9.png)

So, do we want the following to be expanded globally?

    Access
    Format
    Campus
    Media Type
    Call Number

I think that would make the work of having these same facets be the _only_ facets on the homepage and excluding the others _and expanding them by default_ a bit simpler. 

If not, that's fine. But I thought I'd ask because now that I look at all of this I think it's kind of weird we hide our facets results globally and maybe we want to expand them all (or at least just these 5 special ones globally?).

**Comment by cdmo** [comment]
@ruthtillman this is ready to go be merged/deployed but just waiting on decisions around which facets are expanded or collapsed on the homepage and if we put a limit on any (see above). Just wanted to be clear because my above message is a bit unclear.

**Comment by ruthtillman** [comment]
@cdmo ah yes, I never answered this, sorry. The following look good.

```
Access
Format
Campus
Media Type
Call Number
```

If we did fewer, I would suggest:
```
Access
Format
Campus
```

If we limit results, I would suggest maybe... 5? though that could be politically tricky on campus...

**Comment by cdmo** [comment]
ready to be reviewed on qa

**Comment by ruthtillman** [comment]
Looks good on QA! Go ahead with deploy.
