### ISSUE TITLE
856 url exist but not displaying for some records

### ISSUE THREAD

**Issue by mkutch** [psu-libraries/psulib_blacklight#428]
# Issue
856 url exist but not displaying for some records for example catkeys  `2780748`, `7824486`, `7824927`, `7829047`, `7064790`.

Is this an indexing issue or display issue? I noticed that the urls were  Http or HTTP

# WDLL

- [ ]  Update the regex rule to blacklist "ftp" prefix but accept everything else.

**Comment by mkutch** [comment]
Also records with no http in the url but have online content . See catkey `13849535`

**Comment by cdmo** [comment]
Can you tell me if this is related to https://github.com/psu-libraries/psulib_blacklight/issues/352#issuecomment-501858131?

**Comment by cdmo** [comment]
@ruthtillman Do we want to display *anything* that shows up in `856u`? Currently, as @mkutch has discovered here, we aren't getting URLs when the data has odd uppercasing (i.e., "Http" or "HTTP" or "HtTp"). This is an easy fix. However, when the data leaves out the URL prefix entirely, like for [this case](https://catalog.libraries.psu.edu/catalog/13849535/marc_view), our Traject script doesn't pick it up.

The reason for this is that we have a regex rule that looks for http or https pas a prefix followed by some letters and dots to make a website. Why we did this is because of situations where the data shows "ftp://" or other weirdness.

So, I think maybe it makes sense here to change the regex rule to a bad list rule (instead of a good list rule), i.e., we can check if it has an "ftp" prefix and *not accept* that, but accept _everything else_. Thoughts?

Thanks for catching this @mkutch

**Comment by ruthtillman** [comment]
These are all showing, looks good!

**Comment by ruthtillman** [comment]
Also appreciate that the fix is handling any non-http wwws that snuck in! That would be older records, but lord knows we have a ...mix.
