### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#46]
Wiki documentation: https://github.com/psu-libraries/psulib_blacklight/wiki/Advanced-Search

https://github.com/projectblacklight/blacklight_advanced_search

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 2, 2018, 11:59

removed ~1459 label

**Comment by cdmo** [comment]
pr into advanced search gem:

`https://github.com/projectblacklight/blacklight_advanced_search/pull/95`

**Comment by cdmo** [comment]
This seems to fix it https://github.com/projectblacklight/blacklight_advanced_search/issues/96

**Comment by cdmo** [comment]
I am going to assume that we want to implement facets in the advanced search to be chosen.js -style selects rather then checkboxes. If I'm wrong, please let me know. Basing this thought on what our peer institutions are doing and based on my own preference for chosen.js in giant select elements.

**Comment by cdmo** [comment]
@ruthtillman 

Blacklight Advanced Search is setup on my local. It's out-of-the-box in terms of fields. I did add the nice "live type" multiselect thing, which our peers use too. Here are some screenshots. Let me know if you'd like to set the fields now or change anything else now. Or we can hash it out later.

screenshot 1:

![screenshot 2019-01-30 08 33 15](https://user-images.githubusercontent.com/523381/51984715-fc071780-2469-11e9-8660-a04bf8a2bdea.png)

screenshot 2:

![screenshot 2019-01-30 08 33 32](https://user-images.githubusercontent.com/523381/51984721-fe697180-2469-11e9-9001-cadd8bd1405d.png)

**Comment by ruthtillman** [comment]
That looks good! The live multi-select is pretty cool...

re: final fields, those are documented in the wiki...should we start changing those up now or wait until library/location are done?

**Comment by cdmo** [comment]
Awesome, thanks! 

https://github.com/psu-libraries/psulib_blacklight/wiki/Advanced-Search

**Comment by cdmo** [comment]
> Title starts with

This is the only field that we have listed as something you can throw a "starts with" on. Will that always be the case? I'm asking because of the implications on the UI. As in do we want something like 

<img width="703" alt="screenshot 2019-01-30 11 07 24" src="https://user-images.githubusercontent.com/523381/51995431-b3a72400-2480-11e9-96cf-af12ef9850dc.png">

Or are we going with what's out of the box with BLAS, screenshot 1 above.

**Comment by cdmo** [comment]
Going to add ISBN and hold off on everything else for this particular issue. More issues to come.

**Comment by cdmo** [comment]
ISBN/ISSN has been added. I also included catkey as part of the search. Looking at SearchWorks, they included some other items like call number.

**Comment by ruthtillman** [comment]
Reviewing -- there is a problem in the second section with not all fields being available. Besides the drop-downs not showing everything, typing in a field which exists (e.g. a date not listed which does exist as a facet) does not return that date either. We'll need to get this handled for the controlled fields

Per the [Advanced Search wiki page](https://github.com/psu-libraries/psulib_blacklight/wiki/Advanced-Search) the following fields should be fill-in vs. dropdown:

- Subject
- Publication date (perhaps two boxes?)

Remove from drop-down:

- Genre
- Call Number
- Subject (leave in the first section, where it's a fill-in-the-blank

Move Publication date up.

Tackle the problem of not all fields showing up so that:

- Language
- Format

display every value which exists as a facet.

**Comment by banukutlu** [comment]
closing this issue - the above changes will be handled with #239
