### ISSUE TITLE
Seem to have incorrect formats

### ISSUE THREAD

**Issue by mkutch** [psu-libraries/psulib_blacklight#463]
https://catalog.libraries.psu.edu/?f%5Bformat%5D%5B%5D=Archives%2FManuscripts&f%5Bup_library_facet%5D%5B%5D=Pattee+Library+and+Paterno+Library+Stacks&search_field=all_fields

Aha! Link: https://penn-state-university-libraries.aha.io/features/STPROJ-24

**Comment by jeffedmunds** [comment]
@mkutch asked me to look at this issue. Many of the results are due to bad MARC data. Others are due to the fact that cataloging rules allow certain library items to be coded as "mixed materials" (e.g. a children's book accompanied by a plush toy) that are not what most would consider "Archives/Manuscripts" (which can also be coded as "mixed materials"). So this issue is a data issue rather than a code/functionality issue.

**Comment by ruthtillman** [comment]
addressed primarily via data changes and a few logics, will re-open as needed
