### ISSUE TITLE
Temporary: I Want It Button won't work right during upgrade

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#480]
During the upgrade, the "I Want It" button won't work properly. It may redirect people to Test Cat, which will fail to put the item on hold. It may load an error. We aren't sure. How should we deal with this?

Complications:

1. The problem will only exist during the upgrade, approx midnight to noon on Oct 19th.
2. The button must otherwise be usable because it's a core part of our catalog user experience

Because this is a fairly limited problem, we could:

1. Allow a poor user experience during this low-traffic time and hope people understand from the other warnings that this is just a temporary issue 
2. Remove it that night and redeploy on Saturday afternoon
3. Is there a time-based test we temporarily add to determine whether it displays? I know how to do this in PHP. It's not _good_ but would avoid poor user experience and not require an immediate redeploy.

@cdmo @banukutlu I'm leaving this mostly to your judgment.

**Comment by cdmo** [comment]
Thanks @ruthtillman - do we know what the HTTP response will be from the I Want It services? Will it `500`? Or will it `200`?

**Comment by ruthtillman** [comment]
@cdmo I do not know. I believe that Maryam and Todd may have more info on that.

**Comment by cdmo** [comment]
@mkutch can you respond to my question above?

**Comment by tdouty** [comment]
I'm not sure what it will be. Are you using port 28443 or 9443?

**Comment by tdouty** [comment]
9443 is apache http  and 28443 is Tomcat.

**Comment by cdmo** [comment]
Both.

**Comment by banukutlu** [comment]
> 9443 is apache http and 28443 is Tomcat.

talking about ports, which one we should be using? We have `28443` but for items info we do another call with `9443`.

**Comment by cdmo** [comment]
So if I'm reading Ruth's note correctly you're not sure if it will redirect to test-cat? Essentially you don't know what will happen during the outage. Is that right?

The port stuff is for availability lookup info - which is a different issue, right?

**Comment by ruthtillman** [comment]
Seems like convos on here also engage with the question in #479. ... IF we can have someone available on the weekend to load BlackCat on Friday about 8pm with the message and availability turned off and then turn things back on back on Saturday when it's back, then we don't need to build in these different components.

That may not be a thing we can do next time, so if we do it this time we should check on things which don't have existing documentation, like "what happens when _" ... because the ability to redirect to test-cat has always served a set of purposes and documentation for these calls hasn't been needed. But now it is. So even if we go with that method, I think documenting what happens will be a critical part of future-proofing.

**Comment by cdmo** [comment]
I'm not asking about availability, I'm asking about the response expected during the outage for the I Want It button. Do we know what will happen? It sounds like the answer is no, I'm just asking.

**Comment by ruthtillman** [comment]
If we remove availability entirely, as you proposed, I would expect we’d remove this too. But we should document either way.

**Comment by tdouty** [comment]
We looked at this. If you come in on port 28443, it will hit Tomcat which is NOT redirected to the test server. It will try to get information out of Symphony, which will not be up. So, Tomcat is up on port 28443, but it would get errors and I'm not sure what it would return. We could find out by taking Symphony down on the test server and hitting Tomcat on port 28443 to see what it does if you want. If you are hitting port 9443, it will hit the apache web server in an attempt to do a reverse proxy to port 28080. Port 9443 will be open and running and is NOT redirected. We never had to do that for Summon because Maryam would go tot he admin panel and change Summon to hit the test server.  So, port 9443 is open and it will attempt to go to port 28080 for web services. Again, here, Symphony  will not be available so I'm not sure what the response will be. We could try a redirect on port 9443 to go to the test server and it would give back data that is roughly two days old. We never tried a redirect at port 9443, but it should be doable. We would have to test it on the test server to make sure we get it right before attempting it on production.

**Comment by cdmo** [comment]
Thanks @tdouty - this is all information pertaining to web services right? I am asking about the link in "I Want It" for individual records (ie http://cat.libraries.psu.edu/cgi-bin/catredirpg?C=1220805) not web services.

During the outage when I go to http://cat.libraries.psu.edu/cgi-bin/catredirpg?C=1220805 what will happen? This is different from the web service. If we don't know that's totally fine, I was just curious.

**Comment by tdouty** [comment]
Oh, you are doing something different than I thought you were. It looks like you actually display a page in The CAT instead of getting the information from web services and displaying it in your catalog page. You will be re-directed to the test catalog so you will just display that record's holding as it is in test-cat. It will be maybe two days old, but it should work.

**Comment by banukutlu** [comment]
> Oh, you are doing something different than I thought you were. It looks like you actually display a page in The CAT instead of getting the information from web services and displaying it in your catalog page. You will be re-directed to the test catalog so you will just display that record's holding as it is in test-cat. It will be maybe two days old, but it should work.

We are just redirecting to The CAT with the link Charlie mentioned. This is the temporary solution until we implement using the web services.

**Comment by tdouty** [comment]
Ok, something will have to be changed because you are hitting a page behind our code that puts in into read only. Maryam and I are looking at it. Public never can get to this page when we are in read only by going through The CAT.

**Comment by cdmo** [comment]
To be clear, we do not "display a page in The CAT instead of getting the information from web services" - we are using web services. We merely provide a link to the CAT's place a hold page for the I Want It button. See below

<img width="790" alt="Screenshot 2019-10-14 13 54 41" src="https://user-images.githubusercontent.com/523381/66773089-3562a480-ee8c-11e9-94b0-638fe48fa68f.png">

The holding information is all derived from web services, the button with the text "I Want It" is a dynamic link to `http://cat.libraries.psu.edu/cgi-bin/catredirpg?C=CATKEYGOESHERE`

I just want to know what happens when someone goes to that link (i.e., http://cat.libraries.psu.edu/cgi-bin/catredirpg?C=1220805) during the outage.

**Comment by ruthtillman** [comment]
n.b. we are doing what Summon does in terms of linking.

**Comment by cdmo** [comment]
Right, thank @ruthtillman - Summon does the same thing - see the "I Want it" button below:

<img width="821" alt="Screenshot 2019-10-14 14 16 32" src="https://user-images.githubusercontent.com/523381/66773556-4233c800-ee8d-11e9-91cc-07fc477f400c.png">

**Comment by mkutch** [comment]
Yes, but In Summon the "I want it" is disabled during read-only via their Admin panel. See below

![image](https://user-images.githubusercontent.com/43478453/66773906-28df4b80-ee8e-11e9-955a-3026a7f72ba0.png)

**Comment by mkutch** [comment]
So either the "I want it" button will have to be disabled/removed  or CAT redir page has to change just during read only.

**Comment by cdmo** [comment]
The answer is that it redirects to test-cat

**Comment by banukutlu** [comment]
We will not display `Availability` and `I want It` during read-only and display the msg mentioned in #479 on top.
