### ISSUE TITLE
Course Reserves

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#5]
https://github.com/psu-libraries/psulib_blacklight/wiki/Course-Reserves

Aha! Link: https://penn-state-university-libraries.aha.io/features/STPROJ-74

**Comment by ruthtillman** [comment]
Surveying physical reserves...

* Cornell uses something which integrates Blackboard links and other in a searchable interface.
* Duke's physical seems to be split out more and probably won't work for us e.g. https://library.duke.edu/music/reserves
* Brown seems to expect them to be in your syllabus and essentially gives a "use the catalog" message.

**Comment by ruthtillman** [comment]
From our 10/30 meeting. Breaking out structure, problem, and questions in course reserves.

We have two kinds of _thing_ which go on course reserve. The first is existing records, when we already have something, with a full bib record (or purchase the item but get the full bib record), and then put one or more copies on reserve. The second are brief title records, which include title/author/maybe some notes. These are created for items which are specifically added to the catalog to be put on course reserve. They generally are shadowed.

Note, 592s for course reserves/bookplates

# Structure

- we have separate records for course reserves, which have course ID, course description, and course instructor.
- items are linked to these courses in a different module, there's nothing in the 949, other than that the location would be reserve.
- the item ID appears to be the best field for cross-reference.

# Problems

- when we extract a regular bib, we need to indicate if it's on course reserve and link it up with the right course
- we need to extract and index the shadowed brief title records for things like instructor copies
- we will probably need to run a second indexing pass for just course reserve information.

# Questions/Things to Explore

Once we answer these, can people add answers in the comments and check off the item?

[ ] Maryam and Chris: is there a way you can use the Sirsi report selection criteria to figure out how we can extract the brief title records?
[ ] Maryam and Chris: walk through how people make items unavailable/take them off reserve and what this looks like in our data.
[ ] How do we extract and create records _only_ for current courses and remove them when they're done? How do other Sirsi-using institutions, like Stanford (whose course records seem similar to ours) extract and create these records?
[ ] What data fields (location, item ID, etc.?) would we need to extract and how would we index them in order to run a second indexing update process to create/manage course reserves?

Correspondence with Stanford: https://psu.app.box.com/notes/341399689070 & their repo https://github.com/sul-dlss/course_reserves

**Comment by ruthtillman** [comment]
Some more info on function: https://github.com/psu-libraries/psulib_blacklight/wiki/Course-Reserves

**Comment by banukutlu** [comment]
@ruthtillman can you pls spell out the options?

**Comment by ruthtillman** [comment]
Option 1) We continue as things are now in the Cat, with our course reserves in the Blacklight system--similar to Stanford.

Option 2) We find a way to push all our course reserve items from the Cat to Springshare. Critically, we'd need to provide some kind of method for people to know whether items are checked out and how long they can check them out (essentially live availability from Web Services). We can't link to the old Cat, since it will eventually be decommissioned.

Option 3) We start with Option 1, then find a way to display items from Blacklight in Springshare. Simpler problem than just putting the items in Springshare, since we could link to Blacklight for availability portion. However, does require getting them in Blacklight and then pushing to Springshare/updating.

**Comment by cdmo** [comment]
quick question, when we talk about course reserves we're talking about "e-reserves" or physical reserves (like textbooks) or both? I wonder if pulling textbook course reserves out of the catalog would be a problem for the end-user discovery of those items... Removing e-reserves from the catalog (blackcat) seems fine though. 

Is one option "course reserves stay in the catalog" and "e-reserves move entirely to springshare"?

**Comment by ruthtillman** [comment]
working with Springshare on this for now - -- will revisit if needed but otherwise closing
