### ISSUE TITLE
Determine most useful ways to report an issue (Oops!)

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#51]
In GitLab by @rkt6 on Jun 20, 2018, 13:39

Figure out what we need to gather in Oops! forms (such as current URL, browser issues, etc?) and have a way for people to report issues they see.

Aha! Link: https://penn-state-university-libraries.aha.io/features/STPROJ-66

**Comment by ruthtillman** [comment]
Maryam -- is there a way to see if we can generate reports via WebServices? Otherwise we can redo workflow to do it similarly to emailing a copy of the record/link + message.

**Comment by cdmo** [comment]
This should be tied to #50 too right?

**Comment by ruthtillman** [comment]
yes

**Comment by ruthtillman** [comment]
Thinking about this more -- is there a way we can make a feedback form with maybe a drop-down or radio button for reporting an issue -- whether it's a tech issue or a data issue? Data issue would go to ul-cataloging listserv.

Thoughts?

**Comment by cdmo** [comment]
Maybe something down at the bottom of the record view page, like adding a link here:

![Screen Shot 2020-09-28 at 9 06 26 PM](https://user-images.githubusercontent.com/523381/94500931-861efa80-01ce-11eb-9f61-9fe7ca16df71.png)

Maybe a "Report a cataloging issue" or "Report a problem with this record" or something? Since it's just going to an email, not populating some system or database, maybe we can just make the link a simple loaded `mailto`? We can fill out a to, subject and a body. Or we could just put the email address down there like "Email cataloging problems to blah@psu.edu" 🤷 

Then again, judging by the need for "pre-sorting" some of these I wonder if the volume of tickets warrants using one of our helpdesk softwares like ServiceNow or LibAnswers? Then we can rely on that service to produce the form and have it take care of emailing and populating a system with a ticket?

Anyway, just some thoughts

**Comment by mkutch** [comment]
@ruthtillman I asked Sirsi if there was a web service call for the suggestion request in elibrary. They said there is a REST api call and gave some info on it.

**Comment by mkutch** [comment]
These are Suggestion requests that go into the database.  As a user you can also view the requests you put in.

![image](https://user-images.githubusercontent.com/43478453/95607419-b5810300-0a29-11eb-8ec9-5325e249c931.png)

There are people I think in Cataloging that go through the requests and send them to the appropriate people.
