### ISSUE TITLE
Changing I WANT IT links for maps in Catalog to facilitate patron access to non-circulating materials

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/psulib_blacklight#671]
INC1546665

> I saw the presentation about Microforms and requesting microformat scans.  I wonder if we can do something similar.  
> 
> As of now, there is no way for patrons to request access to maps that are pre 1960.  They are classed as MapSpec and don't circulate.
> 
> As most of our map scan requests are for external patrons, we were wondering if we could turn on something that would allow for us to scan for a fee for external patrons.  We currently have a link that patrons can fill out to request maps/prints.  It is possible to turn use that link for our form for patrons to fill out?
> Link to scan request form.
> https://libraries.psu.edu/about/libraries/donald-w-hamer-center-maps-and-geospatial-information/map-scanning-and-printing
> 
> Thanks in advance,
> Heather Ross

**Comment by ruthtillman** [comment]
Emailed Heather to get some details which would allow me to write issue specifications.

**Comment by ruthtillman** [comment]
Details:

## Conditions

LIBRARY: UP-MAPS
and
ITEM TYPE: MAPSPEC

Sample catkeys: `25095210`, `582071`

## Link

https://libraries.psu.edu/about/libraries/donald-w-hamer-center-maps-and-geospatial-information/map-scanning-and-printing

Because this link does not allow parameters to be passed, open in _new window_ so that the person can copy/paste information into it.

**Comment by cdmo** [comment]
I updated the priority on this to 1.0, but the hope is to have this done by end of year

**Comment by cdmo** [comment]
This isn't tied to "ETAS mode" in any way, but is this a separate "old map isn't circulating due to pandemic" mode? Or is this just how things are always with maps that are older than 1960 (i.e., coded `MAPSEC`). I think it's the latter but just wanted to make sure in case we need to be able to switch this on and off based on some situation.

**Comment by cdmo** [comment]
Also, just to verify, "LIBRARY" is `949m` and "ITEM TYPE" is `949u`, right? Going off of https://catalog.libraries.psu.edu/catalog/25095210/marc_view

And one more thing, we can easily modify the Drupal form to accept parameters to pre-fill values if desired. Not sure it would get us a whole lot in this situation since all that is required is the "Call number or title" for 1 to 4 items...

**Comment by ruthtillman** [comment]
949l and 949t!

**Comment by ruthtillman** [comment]
Also no, this is an ongoing thing post ETAS.

**Comment by cdmo** [comment]
Also recording here that we did not intend to prefill the form in Drupal with any values from the catalog record.

**Comment by cdmo** [comment]
Hi @ruthtillman how should we treat records that contain a `MAPSPEC` in addition to other items, like https://catalog.libraries.psu.edu/catalog/24519?

**Comment by ruthtillman** [comment]
Looking at this -- can we just change the ILL Request it's currently doing to the Request scan link? Per convos with Heather, I don't think we want people ILLing them. Her statement was: if they're Penn State, we'll scan it. If they're not, we can't ILL for them anyway and we might scan it for a fee or we might have an already-scanned copy we can provide them. Does that work? 

I think all MAPSPEC now have that ILL link because they're not available available... so do we need to remove it from these?

**Comment by cdmo** [comment]
Ok, so I was planning on this change swapping the "I Want It" button link, but we're thinking we want there to be a link for "request a map scan" at the item level instead?

This record has a `DEPTCHARGE` which is why the special text https://catalog.libraries.psu.edu/catalog/24519
```
949   
a| G5761.F7 1963.G7 index w| LC c| 1 i| 000044512613 d| 5/22/2014 e| 5/22/2014 k| DEPTCHARGE l| MAPS-MP m| UP-MAPS r| M s| Y t| MAPSPEC u| 7/10/2001
```

where this one does not https://catalog.libraries.psu.edu/catalog/25095210
```
949   
a| G3803.W3J3 1956.N4 w| LC c| 1 i| 000080505075 l| MAPS-MP m| UP-MAPS r| Y s| Y t| MAPSPEC u| 11/21/2018
```

**Comment by ruthtillman** [comment]
I had to go review how we did it for Micros, which is what Heather wanted, although I am not 100% sure about replacing the text, but sample: https://catalog.libraries.psu.edu/catalog/13855626

I will check with her whether preferred to replace link or put position below it (as we do with Aeon). One way or another we'll want to indicate it's a scan request, not an ordinary "I Want It" because people may know they can't get the map under normal conditions but then see the scan would be available. I edited the "Details" post farther up this thread and the wiki page with text and a place for position.

**Comment by ruthtillman** [comment]
Heather would like it displayed below the location text, like the Aeon link.

**Comment by cdmo** [comment]
@ruthtillman this in QA and ready for review

**Comment by ruthtillman** [comment]
For the most part looks good but on this one https://blackcat01qa.libraries.psu.edu/catalog/24519 I'm seeing "undefined" following the maps which are in other locations... is that a side-effect bug?

**Comment by cdmo** [comment]
oops🤦 . Nice catch! Will fix and update here when done.

**Comment by cdmo** [comment]
fixed now

**Comment by ruthtillman** [comment]
Reviewed a handful and it looks good to go!
