### ISSUE TITLE
<br> tag in <head><title> for complex faceting

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#674]
When faceting a search to include multiple access facets, I encountered this issue of a `<br>` showing up in the `<head><title>` tag: https://catalog.libraries.psu.edu/?f%5Baccess_facet%5D%5B%5D=Online&f%5Baccess_facet%5D%5B%5D=In+the+Library&f%5Bformat%5D%5B%5D=Journal%2FPeriodical&page=4

not sure what's causing it. Not critical. Troubleshoot someday.

**Comment by nicktiberi** [comment]
So the issue here is that in our `blacklight.en.yml` config, we specify `<br>` as the "word connector" (the config value specifically causing this bug is `two_words_connector`): https://github.com/psu-libraries/psulib_blacklight/blob/main/config/locales/blacklight.en.yml#L57

In the main Blacklight repo, they are using the following code to generate the filter values: https://github.com/projectblacklight/blacklight/blob/822502b197c4c8ef423b9562395b9d1c7e6d41f4/app/helpers/blacklight/catalog_helper_behavior.rb#L309

```
  def render_search_to_page_title_filter(facet, values)
    facet_config = facet_configuration_for_field(facet)
    filter_label = facet_field_label(facet_config.key)
    filter_value = if values.size < 3
                     values.map { |value| facet_item_presenter(facet_config, value, facet).label }.to_sentence
                   else
                     t('blacklight.search.page_title.many_constraint_values', values: values.size)
                   end
    t('blacklight.search.page_title.constraint', label: filter_label, value: filter_value)
  end
```

Specifically, the `to_sentence` method. It is converting an array of length 2 to a sentence, but using `<br>` as the word separator instead of the default ` and `.

If I remove `two_words_connector: "<br>"` from `blacklight.en.yml`, the title looks good, but I don't know what other negative effects this might have elsewhere in the system. I could also fix it by overriding `render_search_to_page_title_filter` in `catalog_helper.rb`.

Possible options:

- stop setting `<br>` as the words connector for the `to_sentence` method
- override `render_search_to_page_title_filter` in `catalog_helper.rb` to stop using `<br>` as a word separator.
- another option I might be missing

@cdmo or @banukutlu - any thoughts? Thanks! 🙂

**Comment by banukutlu** [comment]
Thanks Nick for checking this, fwiw we had the word separator added as part of Item view work here: https://github.com/psu-libraries/psulib_blacklight/pull/336/commits/0c362e5c7ae16ee2b0bad896c91c3f2072e604a6. So, that can be one place to check to see if a change would create any issues.

**Comment by cdmo** [comment]
Nice! 

I can't see any ill-effect for removing the whole support array from the english translation yaml file, I believe this whole chunk can go. Why we set this in the first place isn't coming to mind, and that commit @banukutlu mentioned doesn't seem related. Could be we're just fixing a mistake here. Worth removing, running the test suite and QAing. Always nice to delete.

```yml
  support:
    array:
      words_connector: "<br>"
      two_words_connector: "<br>"
      last_word_connector: "<br>" 
```

**Comment by banukutlu** [comment]
fwiw I remember adding the words_connector back then but I cannot remember exactly for what it is, maybe call number facet  maybe.

**Comment by cdmo** [comment]
I was thinking the same, but didn't see any change after removing the connectors. Maybe this was needed for the previous version of blacklight, before we core blacklight added a nested expand/collapse interior facet that we now use - so something that maybe I missed in replacing our custom approach with the core version several months ago.. possibly

**Comment by banukutlu** [comment]
> I was thinking the same, but didn't see any change after removing the connectors. Maybe this was needed for the previous version of blacklight, before we core blacklight added a nested expand/collapse interior facet that we now use - so something that maybe I missed in replacing our custom approach with the core version several months ago.. possibly

Yeah, this is so possible Charlie, we had that in-place quite a while now and the version of BL we were using was an earlier one at the time and I recall BL making some changes to nested expand/collapse so better to get rid of then if nothing changed 👌  Thanks!

**Comment by cdmo** [comment]
Nothing feels quite so good as pure red (all deletes) PRs ☺️
