### ISSUE TITLE
Determine testing strategy with rspec

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#69]
In GitLab by @bzk60 on Jul 17, 2018, 16:26

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 18, 2018, 14:05

changed title from **{-Investigate R-}spec** to **{+Determine testing strategy with r+}spec**

**Comment by cdmo** [comment]
I started using this: https://collectiveidea.com/blog/archives/2017/02/09/guard-is-your-friend

watched files for changes and runs test automatically

**Comment by cdmo** [comment]
In addition to blacklight-marc having some issues during testing, BL at master does too, a bit anyway. Here are the results of running a test on master:

```
Finished in 9 minutes 49 seconds (files took 2.95 seconds to load)
1098 examples, 9 failures, 6 pending

Failed examples:

rspec ./spec/features/facets_spec.rb:54 # Facets is able to expand facets when javascript is enabled
rspec ./spec/features/search_filters_spec.rb:194 # Facets keeps selected facets expanded on page load
rspec ./spec/features/search_filters_spec.rb:176 # Facets expands when the heading is clicked
rspec ./spec/features/search_filters_spec.rb:169 # Facets is collapsed when not selected
rspec ./spec/features/search_filters_spec.rb:185 # Facets expands when the anchor is clicked
rspec ./spec/features/search_context_spec.rb:25 # Search Results context shows "Back to Search" and "Start Over links"
rspec ./spec/features/search_context_spec.rb:18 # Search Results context redirects context urls to the original url
rspec ./spec/features/search_context_spec.rb:4 # Search Results context passes the current search id through
rspec ./spec/features/search_context_spec.rb:35 # Search Results context navigating between search results using context pagination updates the back to search link with the current search pagination context
```

This is more of an FYI than anything else

**Comment by cdmo** [comment]
related https://github.com/psu-libraries/blacklight-marc/pull/2

**Comment by cdmo** [comment]
So here's what I think we'll be a good start to our rspec setup

1. `rspec-rails` - [use this to generate](https://relishapp.com/rspec/rspec-rails/docs/generators) as needed 
1. `rspec-guard` - see comment above, would be good to add this to the `Procfile.dev` perhaps to run both `rspec` and `niftany`
1. `capybara` - for integration testing
1. I don't think we need pre-commit hooks if we have `guard` watching and we do travis builds when it gets to GH, but, I am not married to this way of thinking.
1. In general, as a philosophy, the more we can do "[Red, Green, Refactor](https://dzone.com/articles/pattern-of-the-month-red-green-refactor)" style of testing, the better. Basically you figure out what it is the user is expecting in the work that is in front of you, then you write a test that fails, then you get the thing to pass, then you can make your code better by refactoring right away or later.

Given that, we need a few new issues to setup guard and capybara as well as integrating guard with our Procfile.dev.

Thoughts?

**Comment by banukutlu** [comment]
Agreed and added #146 and #147.
One though on 5 - It might take some time to reach to that writing tests before implementation but definitely should be our goal.

**Comment by cdmo** [comment]
We still have to figure out the scaffolding needed for solr testing. Lots of other repos and gems do this, so we should be able to borrow and steal.

**Comment by cdmo** [comment]
Looks useful: https://github.com/sul-dlss/rspec-solr

**Comment by cdmo** [comment]
Also instructive: https://github.com/sul-dlss/sw_index_tests

**Comment by cdmo** [comment]
Moar good: https://github.com/tulibraries/tul_cob/blob/master/lib/tasks/server.rake

**Comment by cdmo** [comment]
This is interesting too:

https://github.com/pulibrary/orangelight/tree/master/lib/tasks

https://github.com/pulibrary/orangelight/pull/810/files

**Comment by cdmo** [comment]
I think we can use the Temple COB and the Princeton Orangelight approach to testing solr-related items, they seem like they are about the same. Basically running `run_solr` a locally defined method that warps SolrWrapper (inception!). I tried running `solr:start` directly, but it wants to use the latest version of solr for some reason.  It defines the core correctly and all other config, but not version. Maybe this is part of why they chose to go this way. 

What Stanford's SearchWorks is doing is also interesting and something we can investigate when we're ready.

There are, yet still, a few other things to think about in regards to testing tools: fixtures, factories, data faking, recording (ie., the `vcr` gem). I think what I'll do is make some issues for these, but maybe put them in mvp 1 because it's something we can figure out as we go maybe? Plus I don't want to try and architect The Perfect Testing system forever because, ahem, we won't come close. Better to have a general idea and figure the rest out as we go.

And I will make a new issue for mvp 0 for solr scaffolding for tests. 

Other than that, I think we can close this. @banukutlu your thoughts?

**Comment by cdmo** [comment]
Talked with @banukutlu in zoom, we're good with this as a general strategy and details on other accessories and methods to be addressed as we go
