### ISSUE TITLE
Need better linking to title search

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#889]
This may be solved by @awead moving out the controllers and adding title_sort there? But right now when you search for something like American Marriage https://catalog.qa.k8s.libraries.psu.edu/browse/titles?prefix=american+marriage you get some weird things - try first 2 results.

**Comment by awead** [comment]
This is because the link to the item is being treated as a search term and not a facet. We would need to add `title_sort` as a facet in the controller, which you can do, but the way Solr is processing it is different from other facet fields. We may need to use a new `title_facet` field for this purpose.

**Comment by ruthtillman** [comment]
Is it easy to make title_facet just a duplicate of title_sort so the wheel doesn't have to be reinvented, or is it more complex than that?

**Comment by awead** [comment]
I think the field we use for title browse will _look_ different than `title_sort` because of https://github.com/psu-libraries/psulib_traject/issues/331. But, that field could be the same as `title_sort`. In other words, `title_facet` and `title_sort` can have the same content, which would be different than what it is now, but they will both be configured differently in the Solr schema. The facet field needs to have doc values enabled, but the sort field doesn't.

**Comment by ruthtillman** [comment]
Perfect! Just refreshed my memory of the problem on prod and this fixes it. Thank you!
