### ISSUE TITLE
JavaScript Linting Improvements

### ISSUE THREAD

**Issue by nicktiberi** [psu-libraries/psulib_blacklight#928]
Our JS linting is currently a bit more lax/less opinionated our Ruby linting. Let's investigate some opportunities for improvement there, so we can have more consistent JS + JSX code formatting.

One well-regarded config is AirBNB's: https://www.npmjs.com/package/eslint-config-airbnb

We could also look into using Prettier in our config: https://github.com/prettier/prettier

**Comment by awead** [comment]
The only thing I'd add is that it would be great to have a way of keeping a centralized, versionable config that we could include in all our repositories. This is the idea behind [niftany](https://github.com/psu-libraries/niftany), but JS linting probably doesn't belong in that repo. Speaking of that, if there are better sass linters out there, that'd be great too because the one we're using now doesn't support autocorrect...and that's like whole point of linters in the first place.

**Comment by nicktiberi** [comment]
One possibility is to create our own ESLint config, publish it to NPM, and then use that in every project's .eslintrc:

```
{
    extends: "eslint-config-psulibraries"
}
```
